name: Pull Request

on:
  pull_request:
    branches: [master, main]

jobs:
  validate:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # v7.1.0
        with:
          node-version-file: ".node-version"
          cache: npm
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm test
